/**
 * AUTO-GENERATED — do not edit manually.
 * Text layer prototypes (L5/L6/L7) snapshotted from sample/export_sample.clip.
 *
 * Regenerate: npm run clip:template:build
 */
import type { TextLayerTemplate } from './layerOps';

function b64(value: string): Uint8Array {
  // atob works in browsers, workers, and Node >= 16 (Buffer would break worker bundles).
  const bin = atob(value);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) {
    out[i] = bin.charCodeAt(i);
  }
  return out;
}

function jsonToRow(obj: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [key, val] of Object.entries(obj)) {
    if (val && typeof val === 'object' && '__b64' in val) {
      out[key] = b64(String((val as { __b64: string }).__b64));
    } else {
      out[key] = val;
    }
  }
  return out;
}

function jsonRows(rows: Record<string, unknown>[]): Record<string, unknown>[] {
  return rows.map((row) => jsonToRow(row));
}

type RawSnapshot = {
  layer: Record<string, unknown>;
  blobs: { attributes: { __b64: string }; addAttributes: { __b64: string } };
  mipmapRows: Record<string, unknown>[];
  mipmapInfoRows: Record<string, unknown>[];
  offscreenRows: Record<string, unknown>[];
  thumbnailRows: Record<string, unknown>[];
};

const RAW: Record<'5' | '6' | '7', RawSnapshot> = {
  5:   {
    "layer": {
      "_PW_ID": 5,
      "MainId": 5,
      "CanvasId": 2,
      "LayerName": "あいうえお",
      "LayerType": 0,
      "LayerLock": 0,
      "LayerClip": 0,
      "LayerMasking": 0,
      "LayerOffsetX": 0,
      "LayerOffsetY": 0,
      "LayerRenderOffscrOffsetX": 0,
      "LayerRenderOffscrOffsetY": 0,
      "LayerMaskOffsetX": 0,
      "LayerMaskOffsetY": 0,
      "LayerMaskOffscrOffsetX": 0,
      "LayerMaskOffscrOffsetY": 0,
      "LayerOpacity": 256,
      "LayerComposite": 0,
      "LayerUsePaletteColor": 0,
      "LayerNoticeablePaletteColor": 0,
      "LayerPaletteRed": 0,
      "LayerPaletteGreen": 0,
      "LayerPaletteBlue": 0,
      "LayerFolder": 0,
      "LayerVisibility": 1,
      "LayerSelect": 0,
      "LayerNextIndex": 6,
      "LayerFirstChildIndex": 0,
      "LayerUuid": "cffe6f98ec-f846-20b7-6fe6-5893e6d4d0",
      "LayerRenderMipmap": 5,
      "LayerLayerMaskMipmap": 0,
      "LayerRenderThumbnail": 5,
      "LayerLayerMaskThumbnail": 0,
      "UsePreviewColorType": null,
      "UsePreviewMaskColorType": null,
      "EffectRangeType": null,
      "DraftLayer": null,
      "FilterLayerV132": null,
      "FilterLayerColorMixingInfo": null,
      "GradationFillColorMixingInfo": null,
      "LayerColorTypeIndex": 0,
      "LayerColorTypeBlackChecked": 1,
      "LayerColorTypeWhiteChecked": 1,
      "MaterialContentType": 110,
      "DrawToRenderOffscreenType": 40,
      "DrawToRenderMipmapType": 40,
      "MoveOffsetAndExpandType": 50,
      "TextLayerType": 0,
      "TextLayerString": {
        "__b64": "44GC44GE44GG44GI44GK"
      },
      "TextLayerAttributes": {
        "__b64": "CwAAACIAAAABAAAAAAAAAAUAAAAaAAAAAAAAAAAAAAAAAAAAAAAAAAAAGgAAACAAAAABAAAAAAAAAAUAAAAQAAAAAAAAAAAAWUAAAAAAAABZQBEAAAAAAAAADAAAABIAAAABAAAAAAAAAAUAAAACAAAAAAANAAAAIgAAAAEAAAAAAAAABQAAABIAAAAAAKzVarVarQZAAAAAAAAAWUAOAAAAAAAAABsAAAAAAAAAHAAAAAAAAAAdAAAAEgAAAAEAAAAAAAAABQAAAAIAAAABAEEAAAASAAAAAQAAAAAAAAAFAAAAAgAAAAEAHgAAABQAAAABAAAAAAAAAAUAAAAEAAAAAAAAAA8AAAAAAAAAEwAAAAAAAAAQAAAAAAAAABQAAAAAAAAAEgAAABIAAAABAAAAAAAAAAUAAAACAAAAAAAVAAAAAAAAABYAAAAAAAAAHwAAABkAAABJLU9URuOCouODs+ODgeODg+OCr1N0ZCBCIAAAAAQAAACNAQAAIQAAAAQAAAAQAAAAIgAAAAwAAAAAAAAAAAAAAAAAAAAjAAAABAAAAAAAAAAlAAAABAAAABsBAAAsAAAABAAAAI0gAAAmAAAABAAAAAQAAAArAAAABAAAADIAAAAnAAAACAAAAAUAAAAAAAAAKAAAAAAAAAApAAAAAAAAACoAAAAQAAAAlgMAAP0BAAC3AwAAogIAAC0AAAAEAAAAAAAAAC4AAAAEAAAAAAAAAC8AAAApAAAACQAyAAAAAAAAAB0A77yt77yzIO+8sOOCtOOCt+ODg+OCryDmqJnmupYwAAAABAAAAAEAAAA1AAAABAAAAAAAAAA3AAAABAAAAAAAAAA0AAAABAAAAAEAAAA2AAAAFAAAAAAAAAAAAAAAAAAAAAAAAAD/////OAAAABgAAAAAAAAAkAEAAAIAAAAAAAAAAAAAAAAAAAAxAAAABAAAAOsDAAAyAAAABAAAAAAAAAAzAAAABAAAAAAAAAA5AAAAKwAAAAEAGQBJLU9URuOCouODs+ODgeODg+OCr1N0ZCBCDABJd2FBbnRTdGQtQmQ6AAAABAAAAAgHAAA7AAAABAAAAIQDAAA8AAAABAAAAIQDAAA9AAAABAAAAAAAAAA+AAAABAAAAAAAAAA/AAAACAAAACEAAAClAAAAQAAAACAAAAAc8///AAAAAAAAAAAAAAAAAAAAAHRAAAAc8///dEAAAEIAAAAEAAAAAAAAAEMAAAAEAAAA6AMAAEQAAAAEAAAAAAAAAEUAAAAEAAAAAAAAAEYAAAAIAAAAAAAAAAAAAABHAAAACAAAAEB2gAAAAAAASAAAAAgAAAAhAAAAAAAAAEkAAAAEAAAAAQAAAEoAAAAEAAAAAAAAAA=="
      },
      "TextLayerStringArray": null,
      "TextLayerAttributesArray": null,
      "TextLayerAddAttributesV01": {
        "__b64": "iAMAAAsAAAAWAAAAAQAAAA4AAAAAAAAAAAAAAAAAAAAAABoAAAAMAAAAAQAAAAQAAAAAAAAAEQAAAAAAAAAMAAAADAAAAAEAAAAEAAAAAAAAAA0AAAAMAAAAAQAAAAQAAAAAAAAADgAAAAAAAAAbAAAAAAAAABwAAAAAAAAAHQAAAAwAAAABAAAABAAAAAAAAABBAAAADAAAAAEAAAAEAAAAAAAAAB4AAAAMAAAAAQAAAAQAAAAAAAAADwAAAAAAAAATAAAAAAAAABAAAAAAAAAAFAAAAAAAAAASAAAADAAAAAEAAAAEAAAAAAAAABUAAAAAAAAAFgAAAAAAAAAfAAAAGQAAAEktT1RG44Ki44Oz44OB44OD44KvU3RkIEIgAAAABAAAAI0BAAAhAAAABAAAABAAAAAiAAAADAAAAAAAAAAAAAAAAAAAACMAAAAEAAAAAAAAACUAAAAEAAAAGwEAACwAAAAEAAAAjSAAACYAAAAEAAAABAAAACsAAAAEAAAAMgAAACcAAAAIAAAABQAAAAAAAAAoAAAAAAAAACkAAAAAAAAAKgAAABAAAACWAwAA/QEAALcDAACiAgAALQAAAAQAAAAAAAAALgAAAAQAAAAAAAAALwAAACkAAAAJADIAAAAAAAAAHQDvvK3vvLMg77yw44K044K344OD44KvIOaomea6ljAAAAAEAAAAAQAAADUAAAAEAAAAAAAAADcAAAAEAAAAAAAAADQAAAAEAAAAAQAAADYAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAP////84AAAAGAAAAAAAAACQAQAAAgAAAAAAAAAAAAAAAAAAADEAAAAEAAAA6wMAADIAAAAEAAAAAAAAADMAAAAEAAAAAAAAADkAAAAAAAAAOgAAAAQAAAAIBwAAOwAAAAQAAACEAwAAPAAAAAQAAACEAwAAPQAAAAQAAAAAAAAAPgAAAAQAAAAAAAAAPwAAAAgAAAAhAAAApQAAAEAAAAAgAAAAHPP//wAAAAAAAAAAAAAAAAAAAAB0QAAAHPP//3RAAABCAAAABAAAAAAAAABDAAAABAAAAOgDAABEAAAABAAAAAAAAABFAAAABAAAAAAAAABGAAAACAAAAAAAAAAAAAAARwAAAAgAAABAdoAAAAAAAEgAAAAIAAAAIQAAAAAAAABJAAAABAAAAAEAAABKAAAABAAAAAAAAAA="
      },
      "TextLayerAttributesVersion": 1,
      "TextLayerVersion": null,
      "TextLayerNameAutoChangeEnabled": 1
    },
    "blobs": {
      "attributes": {
        "__b64": "CwAAACIAAAABAAAAAAAAAAUAAAAaAAAAAAAAAAAAAAAAAAAAAAAAAAAAGgAAACAAAAABAAAAAAAAAAUAAAAQAAAAAAAAAAAAWUAAAAAAAABZQBEAAAAAAAAADAAAABIAAAABAAAAAAAAAAUAAAACAAAAAAANAAAAIgAAAAEAAAAAAAAABQAAABIAAAAAAKzVarVarQZAAAAAAAAAWUAOAAAAAAAAABsAAAAAAAAAHAAAAAAAAAAdAAAAEgAAAAEAAAAAAAAABQAAAAIAAAABAEEAAAASAAAAAQAAAAAAAAAFAAAAAgAAAAEAHgAAABQAAAABAAAAAAAAAAUAAAAEAAAAAAAAAA8AAAAAAAAAEwAAAAAAAAAQAAAAAAAAABQAAAAAAAAAEgAAABIAAAABAAAAAAAAAAUAAAACAAAAAAAVAAAAAAAAABYAAAAAAAAAHwAAABkAAABJLU9URuOCouODs+ODgeODg+OCr1N0ZCBCIAAAAAQAAACNAQAAIQAAAAQAAAAQAAAAIgAAAAwAAAAAAAAAAAAAAAAAAAAjAAAABAAAAAAAAAAlAAAABAAAABsBAAAsAAAABAAAAI0gAAAmAAAABAAAAAQAAAArAAAABAAAADIAAAAnAAAACAAAAAUAAAAAAAAAKAAAAAAAAAApAAAAAAAAACoAAAAQAAAAlgMAAP0BAAC3AwAAogIAAC0AAAAEAAAAAAAAAC4AAAAEAAAAAAAAAC8AAAApAAAACQAyAAAAAAAAAB0A77yt77yzIO+8sOOCtOOCt+ODg+OCryDmqJnmupYwAAAABAAAAAEAAAA1AAAABAAAAAAAAAA3AAAABAAAAAAAAAA0AAAABAAAAAEAAAA2AAAAFAAAAAAAAAAAAAAAAAAAAAAAAAD/////OAAAABgAAAAAAAAAkAEAAAIAAAAAAAAAAAAAAAAAAAAxAAAABAAAAOsDAAAyAAAABAAAAAAAAAAzAAAABAAAAAAAAAA5AAAAKwAAAAEAGQBJLU9URuOCouODs+ODgeODg+OCr1N0ZCBCDABJd2FBbnRTdGQtQmQ6AAAABAAAAAgHAAA7AAAABAAAAIQDAAA8AAAABAAAAIQDAAA9AAAABAAAAAAAAAA+AAAABAAAAAAAAAA/AAAACAAAACEAAAClAAAAQAAAACAAAAAc8///AAAAAAAAAAAAAAAAAAAAAHRAAAAc8///dEAAAEIAAAAEAAAAAAAAAEMAAAAEAAAA6AMAAEQAAAAEAAAAAAAAAEUAAAAEAAAAAAAAAEYAAAAIAAAAAAAAAAAAAABHAAAACAAAAEB2gAAAAAAASAAAAAgAAAAhAAAAAAAAAEkAAAAEAAAAAQAAAEoAAAAEAAAAAAAAAA=="
      },
      "addAttributes": {
        "__b64": "iAMAAAsAAAAWAAAAAQAAAA4AAAAAAAAAAAAAAAAAAAAAABoAAAAMAAAAAQAAAAQAAAAAAAAAEQAAAAAAAAAMAAAADAAAAAEAAAAEAAAAAAAAAA0AAAAMAAAAAQAAAAQAAAAAAAAADgAAAAAAAAAbAAAAAAAAABwAAAAAAAAAHQAAAAwAAAABAAAABAAAAAAAAABBAAAADAAAAAEAAAAEAAAAAAAAAB4AAAAMAAAAAQAAAAQAAAAAAAAADwAAAAAAAAATAAAAAAAAABAAAAAAAAAAFAAAAAAAAAASAAAADAAAAAEAAAAEAAAAAAAAABUAAAAAAAAAFgAAAAAAAAAfAAAAGQAAAEktT1RG44Ki44Oz44OB44OD44KvU3RkIEIgAAAABAAAAI0BAAAhAAAABAAAABAAAAAiAAAADAAAAAAAAAAAAAAAAAAAACMAAAAEAAAAAAAAACUAAAAEAAAAGwEAACwAAAAEAAAAjSAAACYAAAAEAAAABAAAACsAAAAEAAAAMgAAACcAAAAIAAAABQAAAAAAAAAoAAAAAAAAACkAAAAAAAAAKgAAABAAAACWAwAA/QEAALcDAACiAgAALQAAAAQAAAAAAAAALgAAAAQAAAAAAAAALwAAACkAAAAJADIAAAAAAAAAHQDvvK3vvLMg77yw44K044K344OD44KvIOaomea6ljAAAAAEAAAAAQAAADUAAAAEAAAAAAAAADcAAAAEAAAAAAAAADQAAAAEAAAAAQAAADYAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAP////84AAAAGAAAAAAAAACQAQAAAgAAAAAAAAAAAAAAAAAAADEAAAAEAAAA6wMAADIAAAAEAAAAAAAAADMAAAAEAAAAAAAAADkAAAAAAAAAOgAAAAQAAAAIBwAAOwAAAAQAAACEAwAAPAAAAAQAAACEAwAAPQAAAAQAAAAAAAAAPgAAAAQAAAAAAAAAPwAAAAgAAAAhAAAApQAAAEAAAAAgAAAAHPP//wAAAAAAAAAAAAAAAAAAAAB0QAAAHPP//3RAAABCAAAABAAAAAAAAABDAAAABAAAAOgDAABEAAAABAAAAAAAAABFAAAABAAAAAAAAABGAAAACAAAAAAAAAAAAAAARwAAAAgAAABAdoAAAAAAAEgAAAAIAAAAIQAAAAAAAABJAAAABAAAAAEAAABKAAAABAAAAAAAAAA="
      }
    },
    "mipmapRows": [
      {
        "_PW_ID": 5,
        "MainId": 5,
        "CanvasId": 2,
        "LayerId": 5,
        "MipmapCount": 6,
        "BaseMipmapInfo": 20
      }
    ],
    "mipmapInfoRows": [
      {
        "_PW_ID": 25,
        "MainId": 20,
        "CanvasId": 2,
        "LayerId": 5,
        "ThisScale": 100,
        "Offscreen": 24,
        "NextIndex": 21
      },
      {
        "_PW_ID": 26,
        "MainId": 21,
        "CanvasId": 2,
        "LayerId": 5,
        "ThisScale": 50,
        "Offscreen": 26,
        "NextIndex": 22
      },
      {
        "_PW_ID": 27,
        "MainId": 22,
        "CanvasId": 2,
        "LayerId": 5,
        "ThisScale": 25,
        "Offscreen": 27,
        "NextIndex": 23
      },
      {
        "_PW_ID": 28,
        "MainId": 23,
        "CanvasId": 2,
        "LayerId": 5,
        "ThisScale": 12.5,
        "Offscreen": 28,
        "NextIndex": 24
      },
      {
        "_PW_ID": 29,
        "MainId": 24,
        "CanvasId": 2,
        "LayerId": 5,
        "ThisScale": 6.25,
        "Offscreen": 29,
        "NextIndex": 25
      },
      {
        "_PW_ID": 30,
        "MainId": 25,
        "CanvasId": 2,
        "LayerId": 5,
        "ThisScale": 3.125,
        "Offscreen": 30,
        "NextIndex": 0
      }
    ],
    "offscreenRows": [
      {
        "_PW_ID": 29,
        "MainId": 24,
        "CanvasId": 2,
        "LayerId": 5,
        "Attribute": {
          "__b64": "AAAAEAAAAGYAAAAqAAAA+gAAAAkAUABhAHIAYQBtAGUAdABlAHIAAAXuAAAIZgAAAAYAAAAJAAAAIQAAAAEAAAAEAAAABQABAAAAAAAEAAAEAAAAAAEAAAEAAAEAAAAAAQAAAAEAAAAACAAAAAgAAAAAAAAAAAAAAAkASQBuAGkAdABDAG8AbABvAHIAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAkAQgBsAG8AYwBrAFMAaQB6AGUAAAAMAAAANgAAAAQAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAAYzAAAAaAAAAGgAAABoAAAAaAAAAGgAABEXAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGg="
        },
        "BlockData": {
          "__b64": "ZXh0cm5saWRGM0U3QTlFNUEzNTY0NUQ2QkI3RTVDQ0IzMDYzQUIwRA=="
        }
      },
      {
        "_PW_ID": 30,
        "MainId": 26,
        "CanvasId": 2,
        "LayerId": 5,
        "Attribute": {
          "__b64": "AAAAEAAAAGYAAAAqAAAAXgAAAAkAUABhAHIAYQBtAGUAdABlAHIAAAL3AAAEMwAAAAMAAAAFAAAAIQAAAAEAAAAEAAAABQABAAAAAAAEAAAEAAAAAAEAAAEAAAEAAAAAAQAAAAEAAAAACAAAAAgAAAAAAAAAAAAAAAkASQBuAGkAdABDAG8AbABvAHIAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAkAQgBsAG8AYwBrAFMAaQB6AGUAAAAMAAAADwAAAAQAAABoAAAHbgAAAGgAAABoAAAPCQAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGg="
        },
        "BlockData": {
          "__b64": "ZXh0cm5saWQ4RTExNzI3NDREMzY0MThEODc5RjQyNkM2QkU1RUQ0Qg=="
        }
      },
      {
        "_PW_ID": 31,
        "MainId": 27,
        "CanvasId": 2,
        "LayerId": 5,
        "Attribute": {
          "__b64": "AAAAEAAAAGYAAAAqAAAAOgAAAAkAUABhAHIAYQBtAGUAdABlAHIAAAF7AAACGQAAAAIAAAADAAAAIQAAAAEAAAAEAAAABQABAAAAAAAEAAAEAAAAAAEAAAEAAAEAAAAAAQAAAAEAAAAACAAAAAgAAAAAAAAAAAAAAAkASQBuAGkAdABDAG8AbABvAHIAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAkAQgBsAG8AYwBrAFMAaQB6AGUAAAAMAAAABgAAAAQAAArtAAAAaAAAAGgAAABoAAAAaAAAAGg="
        },
        "BlockData": {
          "__b64": "ZXh0cm5saWRGRkJEMzUxMUZFNTY0NEVBQTY5MTQzRjc0RDk4RUIzQg=="
        }
      },
      {
        "_PW_ID": 32,
        "MainId": 28,
        "CanvasId": 2,
        "LayerId": 5,
        "Attribute": {
          "__b64": "AAAAEAAAAGYAAAAqAAAAKgAAAAkAUABhAHIAYQBtAGUAdABlAHIAAAC9AAABDAAAAAEAAAACAAAAIQAAAAEAAAAEAAAABQABAAAAAAAEAAAEAAAAAAEAAAEAAAEAAAAAAQAAAAEAAAAACAAAAAgAAAAAAAAAAAAAAAkASQBuAGkAdABDAG8AbABvAHIAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAkAQgBsAG8AYwBrAFMAaQB6AGUAAAAMAAAAAgAAAAQAAAdRAAAAaA=="
        },
        "BlockData": {
          "__b64": "ZXh0cm5saWQ0RTVFOEVDQzdFMjI0MjI2QTM2Q0I5RTgwMTY5MTVDQw=="
        }
      },
      {
        "_PW_ID": 33,
        "MainId": 29,
        "CanvasId": 2,
        "LayerId": 5,
        "Attribute": {
          "__b64": "AAAAEAAAAGYAAAAqAAAAJgAAAAkAUABhAHIAYQBtAGUAdABlAHIAAABeAAAAhgAAAAEAAAABAAAAIQAAAAEAAAAEAAAABQABAAAAAAAEAAAEAAAAAAEAAAEAAAEAAAAAAQAAAAEAAAAACAAAAAgAAAAAAAAAAAAAAAkASQBuAGkAdABDAG8AbABvAHIAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAkAQgBsAG8AYwBrAFMAaQB6AGUAAAAMAAAAAQAAAAQAAAdM"
        },
        "BlockData": {
          "__b64": "ZXh0cm5saWQ5MjNCNzQ5QUM5RTk0NTVCQTNDRjJFQjZCRENBMUVCRg=="
        }
      },
      {
        "_PW_ID": 34,
        "MainId": 30,
        "CanvasId": 2,
        "LayerId": 5,
        "Attribute": {
          "__b64": "AAAAEAAAAGYAAAAqAAAAJgAAAAkAUABhAHIAYQBtAGUAdABlAHIAAAAvAAAAQwAAAAEAAAABAAAAIQAAAAEAAAAEAAAABQABAAAAAAAEAAAEAAAAAAEAAAEAAAEAAAAAAQAAAAEAAAAACAAAAAgAAAAAAAAAAAAAAAkASQBuAGkAdABDAG8AbABvAHIAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAkAQgBsAG8AYwBrAFMAaQB6AGUAAAAMAAAAAQAAAAQAAAZI"
        },
        "BlockData": {
          "__b64": "ZXh0cm5saWQzRDY4OUQ5QUZENTY0MzhCOUIwQzM3MjM3NkJBQTYxNA=="
        }
      },
      {
        "_PW_ID": 35,
        "MainId": 25,
        "CanvasId": 2,
        "LayerId": 5,
        "Attribute": {
          "__b64": "AAAAEAAAAGYAAAAqAAAAMgAAAAkAUABhAHIAYQBtAGUAdABlAHIAAAIAAAACAAAAAAIAAAACAAAAIQAAAAEAAAAEAAAABQABAAAAAAAEAAAEAAAAAAEAAAEAAAEAAAAAAQAAAAEAAAAACAAAAAgAAAAAAAAAAAAAAAkASQBuAGkAdABDAG8AbABvAHIAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAkAQgBsAG8AYwBrAFMAaQB6AGUAAAAMAAAABAAAAAQAAABoAAATqgAAAGgAAABo"
        },
        "BlockData": {
          "__b64": "ZXh0cm5saWQ2MEVCMDQzQTM4Q0Y0NzdDQTVDNkU3QTA2QjNGQTI5RA=="
        }
      }
    ],
    "thumbnailRows": [
      {
        "_PW_ID": 5,
        "MainId": 5,
        "CanvasId": 2,
        "LayerId": 5,
        "ThumbnailSmallerNeedRefresh": 19,
        "ThumbnailSmallNeedRefresh": 19,
        "ThumbnailMiddleNeedRefresh": 19,
        "ThumbnailLargeNeedRefresh": 19,
        "ThumbnailLargerNeedRefresh": 19,
        "ThumbnailMiddle2xNeedRefresh": 19,
        "ThumbnailLarger2xNeedRefresh": 19,
        "ThumbnailSmallerNeedRefresh1": 0,
        "ThumbnailSmallNeedRefresh1": 20,
        "ThumbnailMiddleNeedRefresh1": 20,
        "ThumbnailLargeNeedRefresh1": 20,
        "ThumbnailLargerNeedRefresh1": 0,
        "ThumbnailMiddle2xNeedRefresh1": 20,
        "ThumbnailLarger2xNeedRefresh1": 20,
        "ThumbnailDrewMode": 0,
        "ThumbnailFixMode": 0,
        "ThumbnailCanvasWidth": 1518,
        "ThumbnailCanvasHeight": 2150,
        "ThumbnailUseDrawColor": 0,
        "ThumbnailMainColorRed": 0,
        "ThumbnailMainColorGreen": 0,
        "ThumbnailMainColorBlue": 0,
        "ThumbnailSubColorRed": 0,
        "ThumbnailSubColorGreen": 0,
        "ThumbnailSubColorBlue": 0,
        "ThumbnailOffscreen": 25,
        "ThumbnailColorTypeIndex": 0,
        "ThumbnailColorTypeBlack": 1,
        "ThumbnailColorTypeWhite": 1,
        "ThumbnailPrewviewColorTypeIndex": 0,
        "ThumbnailPrewviewColorTypeBlack": 1,
        "ThumbnailPrewviewColorTypeWhite": 1,
        "ThumbnailPrewviewColorTypeOpacity": 1,
        "ThumbnailPrewviewColorTypeImage": 2147483648,
        "ThumbnailPrewviewColorTypeAlpha": 2147483648,
        "ThumbnailPrewviewMaskBinarize": 0,
        "ThumbnailPrewviewMaskThreshold": 2147483648,
        "ThumbnailDrewUseCanvasAspect0": 1,
        "ThumbnailDrewUseCanvasAspect1": 0
      }
    ]
  },
  6:   {
    "layer": {
      "_PW_ID": 6,
      "MainId": 6,
      "CanvasId": 2,
      "LayerName": "こんにちは さようなら",
      "LayerType": 0,
      "LayerLock": 0,
      "LayerClip": 0,
      "LayerMasking": 0,
      "LayerOffsetX": -415,
      "LayerOffsetY": 157,
      "LayerRenderOffscrOffsetX": 415,
      "LayerRenderOffscrOffsetY": -157,
      "LayerMaskOffsetX": 415,
      "LayerMaskOffsetY": -157,
      "LayerMaskOffscrOffsetX": 0,
      "LayerMaskOffscrOffsetY": 0,
      "LayerOpacity": 256,
      "LayerComposite": 0,
      "LayerUsePaletteColor": 0,
      "LayerNoticeablePaletteColor": 0,
      "LayerPaletteRed": 0,
      "LayerPaletteGreen": 0,
      "LayerPaletteBlue": 0,
      "LayerFolder": 0,
      "LayerVisibility": 1,
      "LayerSelect": 0,
      "LayerNextIndex": 7,
      "LayerFirstChildIndex": 0,
      "LayerUuid": "64a412ba2c-6c4a-5d8b-0c55-3634c1de07",
      "LayerRenderMipmap": 6,
      "LayerLayerMaskMipmap": 0,
      "LayerRenderThumbnail": 6,
      "LayerLayerMaskThumbnail": 0,
      "UsePreviewColorType": null,
      "UsePreviewMaskColorType": null,
      "EffectRangeType": null,
      "DraftLayer": null,
      "FilterLayerV132": null,
      "FilterLayerColorMixingInfo": null,
      "GradationFillColorMixingInfo": null,
      "LayerColorTypeIndex": 0,
      "LayerColorTypeBlackChecked": 1,
      "LayerColorTypeWhiteChecked": 1,
      "MaterialContentType": 110,
      "DrawToRenderOffscreenType": 40,
      "DrawToRenderMipmapType": 40,
      "MoveOffsetAndExpandType": 50,
      "TextLayerType": 0,
      "TextLayerString": {
        "__b64": "44GT44KT44Gr44Gh44GvDQrjgZXjgojjgYbjgarjgok="
      },
      "TextLayerAttributes": {
        "__b64": "CwAAACIAAAABAAAAAAAAAAwAAAAaAAAAAAAAAAAAAAAAAAAAAAAAAAAAGgAAACAAAAABAAAAAAAAAAwAAAAQAAAAAAAAAAAAWUAAAAAAAABZQBEAAAAAAAAADAAAABIAAAABAAAAAAAAAAwAAAACAAAAAAANAAAAIgAAAAEAAAAAAAAADAAAABIAAAAAAKzVarVarQZAAAAAAAAAWUAOAAAAAAAAABsAAAAAAAAAHAAAAAAAAAAdAAAAEgAAAAEAAAAAAAAADAAAAAIAAAABAEEAAAASAAAAAQAAAAAAAAAMAAAAAgAAAAEAHgAAABQAAAABAAAAAAAAAAwAAAAEAAAAAAAAAA8AAAAAAAAAEwAAAAAAAAAQAAAAAAAAABQAAAAAAAAAEgAAABIAAAABAAAAAAAAAAwAAAACAAAAAAAVAAAAAAAAABYAAAAAAAAAHwAAABkAAABJLU9URuOCouODs+ODgeODg+OCr1N0ZCBCIAAAAAQAAACNAQAAIQAAAAQAAAAQAAAAIgAAAAwAAAAAAAAAAAAAAAAAAAAjAAAABAAAAAAAAAAlAAAABAAAABsBAAAsAAAABAAAAI0gAAAmAAAABAAAAAQAAAArAAAABAAAADIAAAAnAAAACAAAAAwAAAAAAAAAKAAAAAAAAAApAAAAAAAAACoAAAAQAAAAXAMAAP0BAAC3AwAApAIAAC0AAAAEAAAAAAAAAC4AAAAEAAAAAAAAAC8AAAApAAAACQAyAAAAAAAAAB0A77yt77yzIO+8sOOCtOOCt+ODg+OCryDmqJnmupYwAAAABAAAAAEAAAA1AAAABAAAAAAAAAA3AAAABAAAAAAAAAA0AAAABAAAAAEAAAA2AAAAFAAAAAAAAAAAAAAAAAAAAAAAAAD/////OAAAABgAAAAAAAAAkAEAAAIAAAAAAAAAAAAAAAAAAAAxAAAABAAAAOsDAAAyAAAABAAAAAAAAAAzAAAABAAAAAAAAAA5AAAAKwAAAAEAGQBJLU9URuOCouODs+ODgeODg+OCr1N0ZCBCDABJd2FBbnRTdGQtQmQ6AAAABAAAAAgHAAA7AAAABAAAAIQDAAA8AAAABAAAAIQDAAA9AAAABAAAAAAAAAA+AAAABAAAAAAAAAA/AAAACAAAAFsAAACnAAAAQAAAACAAAADY3P//AAAAAGQAAAAAAAAAZAAAADxBAADY3P//PEEAAEIAAAAEAAAAAAAAAEMAAAAEAAAA6AMAAEQAAAAEAAAAAAAAAEUAAAAEAAAAAAAAAEYAAAAIAAAAAAAAAAAAAABHAAAACAAAAEB2gAAAAAAASAAAAAgAAABaAAAAAAAAAEkAAAAEAAAAAQAAAEoAAAAEAAAAAAAAAA=="
      },
      "TextLayerStringArray": null,
      "TextLayerAttributesArray": null,
      "TextLayerAddAttributesV01": {
        "__b64": "iAMAAAsAAAAWAAAAAQAAAA4AAAAAAAAAAAAAAAAAAAAAABoAAAAMAAAAAQAAAAQAAAAAAAAAEQAAAAAAAAAMAAAADAAAAAEAAAAEAAAAAAAAAA0AAAAMAAAAAQAAAAQAAAAAAAAADgAAAAAAAAAbAAAAAAAAABwAAAAAAAAAHQAAAAwAAAABAAAABAAAAAAAAABBAAAADAAAAAEAAAAEAAAAAAAAAB4AAAAMAAAAAQAAAAQAAAAAAAAADwAAAAAAAAATAAAAAAAAABAAAAAAAAAAFAAAAAAAAAASAAAADAAAAAEAAAAEAAAAAAAAABUAAAAAAAAAFgAAAAAAAAAfAAAAGQAAAEktT1RG44Ki44Oz44OB44OD44KvU3RkIEIgAAAABAAAAI0BAAAhAAAABAAAABAAAAAiAAAADAAAAAAAAAAAAAAAAAAAACMAAAAEAAAAAAAAACUAAAAEAAAAGwEAACwAAAAEAAAAjSAAACYAAAAEAAAABAAAACsAAAAEAAAAMgAAACcAAAAIAAAADAAAAAAAAAAoAAAAAAAAACkAAAAAAAAAKgAAABAAAABcAwAA/QEAALcDAACkAgAALQAAAAQAAAAAAAAALgAAAAQAAAAAAAAALwAAACkAAAAJADIAAAAAAAAAHQDvvK3vvLMg77yw44K044K344OD44KvIOaomea6ljAAAAAEAAAAAQAAADUAAAAEAAAAAAAAADcAAAAEAAAAAAAAADQAAAAEAAAAAQAAADYAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAP////84AAAAGAAAAAAAAACQAQAAAgAAAAAAAAAAAAAAAAAAADEAAAAEAAAA6wMAADIAAAAEAAAAAAAAADMAAAAEAAAAAAAAADkAAAAAAAAAOgAAAAQAAAAIBwAAOwAAAAQAAACEAwAAPAAAAAQAAACEAwAAPQAAAAQAAAAAAAAAPgAAAAQAAAAAAAAAPwAAAAgAAABbAAAApwAAAEAAAAAgAAAA2Nz//wAAAABkAAAAAAAAAGQAAAA8QQAA2Nz//zxBAABCAAAABAAAAAAAAABDAAAABAAAAOgDAABEAAAABAAAAAAAAABFAAAABAAAAAAAAABGAAAACAAAAAAAAAAAAAAARwAAAAgAAABAdoAAAAAAAEgAAAAIAAAAWgAAAAAAAABJAAAABAAAAAEAAABKAAAABAAAAAAAAAA="
      },
      "TextLayerAttributesVersion": 1,
      "TextLayerVersion": null,
      "TextLayerNameAutoChangeEnabled": 1
    },
    "blobs": {
      "attributes": {
        "__b64": "CwAAACIAAAABAAAAAAAAAAwAAAAaAAAAAAAAAAAAAAAAAAAAAAAAAAAAGgAAACAAAAABAAAAAAAAAAwAAAAQAAAAAAAAAAAAWUAAAAAAAABZQBEAAAAAAAAADAAAABIAAAABAAAAAAAAAAwAAAACAAAAAAANAAAAIgAAAAEAAAAAAAAADAAAABIAAAAAAKzVarVarQZAAAAAAAAAWUAOAAAAAAAAABsAAAAAAAAAHAAAAAAAAAAdAAAAEgAAAAEAAAAAAAAADAAAAAIAAAABAEEAAAASAAAAAQAAAAAAAAAMAAAAAgAAAAEAHgAAABQAAAABAAAAAAAAAAwAAAAEAAAAAAAAAA8AAAAAAAAAEwAAAAAAAAAQAAAAAAAAABQAAAAAAAAAEgAAABIAAAABAAAAAAAAAAwAAAACAAAAAAAVAAAAAAAAABYAAAAAAAAAHwAAABkAAABJLU9URuOCouODs+ODgeODg+OCr1N0ZCBCIAAAAAQAAACNAQAAIQAAAAQAAAAQAAAAIgAAAAwAAAAAAAAAAAAAAAAAAAAjAAAABAAAAAAAAAAlAAAABAAAABsBAAAsAAAABAAAAI0gAAAmAAAABAAAAAQAAAArAAAABAAAADIAAAAnAAAACAAAAAwAAAAAAAAAKAAAAAAAAAApAAAAAAAAACoAAAAQAAAAXAMAAP0BAAC3AwAApAIAAC0AAAAEAAAAAAAAAC4AAAAEAAAAAAAAAC8AAAApAAAACQAyAAAAAAAAAB0A77yt77yzIO+8sOOCtOOCt+ODg+OCryDmqJnmupYwAAAABAAAAAEAAAA1AAAABAAAAAAAAAA3AAAABAAAAAAAAAA0AAAABAAAAAEAAAA2AAAAFAAAAAAAAAAAAAAAAAAAAAAAAAD/////OAAAABgAAAAAAAAAkAEAAAIAAAAAAAAAAAAAAAAAAAAxAAAABAAAAOsDAAAyAAAABAAAAAAAAAAzAAAABAAAAAAAAAA5AAAAKwAAAAEAGQBJLU9URuOCouODs+ODgeODg+OCr1N0ZCBCDABJd2FBbnRTdGQtQmQ6AAAABAAAAAgHAAA7AAAABAAAAIQDAAA8AAAABAAAAIQDAAA9AAAABAAAAAAAAAA+AAAABAAAAAAAAAA/AAAACAAAAFsAAACnAAAAQAAAACAAAADY3P//AAAAAGQAAAAAAAAAZAAAADxBAADY3P//PEEAAEIAAAAEAAAAAAAAAEMAAAAEAAAA6AMAAEQAAAAEAAAAAAAAAEUAAAAEAAAAAAAAAEYAAAAIAAAAAAAAAAAAAABHAAAACAAAAEB2gAAAAAAASAAAAAgAAABaAAAAAAAAAEkAAAAEAAAAAQAAAEoAAAAEAAAAAAAAAA=="
      },
      "addAttributes": {
        "__b64": "iAMAAAsAAAAWAAAAAQAAAA4AAAAAAAAAAAAAAAAAAAAAABoAAAAMAAAAAQAAAAQAAAAAAAAAEQAAAAAAAAAMAAAADAAAAAEAAAAEAAAAAAAAAA0AAAAMAAAAAQAAAAQAAAAAAAAADgAAAAAAAAAbAAAAAAAAABwAAAAAAAAAHQAAAAwAAAABAAAABAAAAAAAAABBAAAADAAAAAEAAAAEAAAAAAAAAB4AAAAMAAAAAQAAAAQAAAAAAAAADwAAAAAAAAATAAAAAAAAABAAAAAAAAAAFAAAAAAAAAASAAAADAAAAAEAAAAEAAAAAAAAABUAAAAAAAAAFgAAAAAAAAAfAAAAGQAAAEktT1RG44Ki44Oz44OB44OD44KvU3RkIEIgAAAABAAAAI0BAAAhAAAABAAAABAAAAAiAAAADAAAAAAAAAAAAAAAAAAAACMAAAAEAAAAAAAAACUAAAAEAAAAGwEAACwAAAAEAAAAjSAAACYAAAAEAAAABAAAACsAAAAEAAAAMgAAACcAAAAIAAAADAAAAAAAAAAoAAAAAAAAACkAAAAAAAAAKgAAABAAAABcAwAA/QEAALcDAACkAgAALQAAAAQAAAAAAAAALgAAAAQAAAAAAAAALwAAACkAAAAJADIAAAAAAAAAHQDvvK3vvLMg77yw44K044K344OD44KvIOaomea6ljAAAAAEAAAAAQAAADUAAAAEAAAAAAAAADcAAAAEAAAAAAAAADQAAAAEAAAAAQAAADYAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAP////84AAAAGAAAAAAAAACQAQAAAgAAAAAAAAAAAAAAAAAAADEAAAAEAAAA6wMAADIAAAAEAAAAAAAAADMAAAAEAAAAAAAAADkAAAAAAAAAOgAAAAQAAAAIBwAAOwAAAAQAAACEAwAAPAAAAAQAAACEAwAAPQAAAAQAAAAAAAAAPgAAAAQAAAAAAAAAPwAAAAgAAABbAAAApwAAAEAAAAAgAAAA2Nz//wAAAABkAAAAAAAAAGQAAAA8QQAA2Nz//zxBAABCAAAABAAAAAAAAABDAAAABAAAAOgDAABEAAAABAAAAAAAAABFAAAABAAAAAAAAABGAAAACAAAAAAAAAAAAAAARwAAAAgAAABAdoAAAAAAAEgAAAAIAAAAWgAAAAAAAABJAAAABAAAAAEAAABKAAAABAAAAAAAAAA="
      }
    },
    "mipmapRows": [
      {
        "_PW_ID": 6,
        "MainId": 6,
        "CanvasId": 2,
        "LayerId": 6,
        "MipmapCount": 6,
        "BaseMipmapInfo": 26
      }
    ],
    "mipmapInfoRows": [
      {
        "_PW_ID": 31,
        "MainId": 26,
        "CanvasId": 2,
        "LayerId": 6,
        "ThisScale": 100,
        "Offscreen": 32,
        "NextIndex": 27
      },
      {
        "_PW_ID": 32,
        "MainId": 27,
        "CanvasId": 2,
        "LayerId": 6,
        "ThisScale": 50,
        "Offscreen": 34,
        "NextIndex": 28
      },
      {
        "_PW_ID": 33,
        "MainId": 28,
        "CanvasId": 2,
        "LayerId": 6,
        "ThisScale": 25,
        "Offscreen": 35,
        "NextIndex": 29
      },
      {
        "_PW_ID": 34,
        "MainId": 29,
        "CanvasId": 2,
        "LayerId": 6,
        "ThisScale": 12.5,
        "Offscreen": 36,
        "NextIndex": 30
      },
      {
        "_PW_ID": 35,
        "MainId": 30,
        "CanvasId": 2,
        "LayerId": 6,
        "ThisScale": 6.25,
        "Offscreen": 37,
        "NextIndex": 31
      },
      {
        "_PW_ID": 36,
        "MainId": 31,
        "CanvasId": 2,
        "LayerId": 6,
        "ThisScale": 3.125,
        "Offscreen": 38,
        "NextIndex": 0
      }
    ],
    "offscreenRows": [
      {
        "_PW_ID": 37,
        "MainId": 32,
        "CanvasId": 2,
        "LayerId": 6,
        "Attribute": {
          "__b64": "AAAAEAAAAGYAAAAqAAAA+gAAAAkAUABhAHIAYQBtAGUAdABlAHIAAAXuAAAIZgAAAAYAAAAJAAAAIQAAAAEAAAAEAAAABQABAAAAAAAEAAAEAAAAAAEAAAEAAAEAAAAAAQAAAAEAAAAACAAAAAgAAAAAAAAAAAAAAAkASQBuAGkAdABDAG8AbABvAHIAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAkAQgBsAG8AYwBrAFMAaQB6AGUAAAAMAAAANgAAAAQAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAAYdAAAAaAAAAGgAAABoAAAOKQAACdYAAAYdAAAAaAAAAGgAAABoAAAMkQAACbgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGg="
        },
        "BlockData": {
          "__b64": "ZXh0cm5saWQ5MjhDNjdEMzgzNTI0QzE0QkFFMzgwNUFDMjM2QjVDNQ=="
        }
      },
      {
        "_PW_ID": 38,
        "MainId": 34,
        "CanvasId": 2,
        "LayerId": 6,
        "Attribute": {
          "__b64": "AAAAEAAAAGYAAAAqAAAAXgAAAAkAUABhAHIAYQBtAGUAdABlAHIAAAL3AAAEMwAAAAMAAAAFAAAAIQAAAAEAAAAEAAAABQABAAAAAAAEAAAEAAAAAAEAAAEAAAEAAAAAAQAAAAEAAAAACAAAAAgAAAAAAAAAAAAAAAkASQBuAGkAdABDAG8AbABvAHIAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAkAQgBsAG8AYwBrAFMAaQB6AGUAAAAMAAAADwAAAAQAAABoAAAGJwAAAGgAABKEAAASKgAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGg="
        },
        "BlockData": {
          "__b64": "ZXh0cm5saWRFQjVCNjIwMkYyNUI0ODFFQjkwREQ5MURDRDNCQzU1QQ=="
        }
      },
      {
        "_PW_ID": 39,
        "MainId": 35,
        "CanvasId": 2,
        "LayerId": 6,
        "Attribute": {
          "__b64": "AAAAEAAAAGYAAAAqAAAAOgAAAAkAUABhAHIAYQBtAGUAdABlAHIAAAF7AAACGQAAAAIAAAADAAAAIQAAAAEAAAAEAAAABQABAAAAAAAEAAAEAAAAAAEAAAEAAAEAAAAAAQAAAAEAAAAACAAAAAgAAAAAAAAAAAAAAAkASQBuAGkAdABDAG8AbABvAHIAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAkAQgBsAG8AYwBrAFMAaQB6AGUAAAAMAAAABgAAAAQAAAuDAAAAaAAAAGgAAABoAAAAaAAAAGg="
        },
        "BlockData": {
          "__b64": "ZXh0cm5saWRBNDlCNTQ2M0Q3N0U0QjBEOTdGNTkyMEY4MkYyQzE1Qw=="
        }
      },
      {
        "_PW_ID": 40,
        "MainId": 36,
        "CanvasId": 2,
        "LayerId": 6,
        "Attribute": {
          "__b64": "AAAAEAAAAGYAAAAqAAAAKgAAAAkAUABhAHIAYQBtAGUAdABlAHIAAAC9AAABDAAAAAEAAAACAAAAIQAAAAEAAAAEAAAABQABAAAAAAAEAAAEAAAAAAEAAAEAAAEAAAAAAQAAAAEAAAAACAAAAAgAAAAAAAAAAAAAAAkASQBuAGkAdABDAG8AbABvAHIAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAkAQgBsAG8AYwBrAFMAaQB6AGUAAAAMAAAAAgAAAAQAAA3IAAAAaA=="
        },
        "BlockData": {
          "__b64": "ZXh0cm5saWRFNUQ3MUI5RDkzRTQ0OTg5OUE0OTk4NUM2OTAzOTExOA=="
        }
      },
      {
        "_PW_ID": 41,
        "MainId": 37,
        "CanvasId": 2,
        "LayerId": 6,
        "Attribute": {
          "__b64": "AAAAEAAAAGYAAAAqAAAAJgAAAAkAUABhAHIAYQBtAGUAdABlAHIAAABeAAAAhgAAAAEAAAABAAAAIQAAAAEAAAAEAAAABQABAAAAAAAEAAAEAAAAAAEAAAEAAAEAAAAAAQAAAAEAAAAACAAAAAgAAAAAAAAAAAAAAAkASQBuAGkAdABDAG8AbABvAHIAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAkAQgBsAG8AYwBrAFMAaQB6AGUAAAAMAAAAAQAAAAQAAAoW"
        },
        "BlockData": {
          "__b64": "ZXh0cm5saWQzOTdEOUM0RDBDNTU0NkY1QUE1REE3NDRGODI3M0IzOQ=="
        }
      },
      {
        "_PW_ID": 42,
        "MainId": 38,
        "CanvasId": 2,
        "LayerId": 6,
        "Attribute": {
          "__b64": "AAAAEAAAAGYAAAAqAAAAJgAAAAkAUABhAHIAYQBtAGUAdABlAHIAAAAvAAAAQwAAAAEAAAABAAAAIQAAAAEAAAAEAAAABQABAAAAAAAEAAAEAAAAAAEAAAEAAAEAAAAAAQAAAAEAAAAACAAAAAgAAAAAAAAAAAAAAAkASQBuAGkAdABDAG8AbABvAHIAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAkAQgBsAG8AYwBrAFMAaQB6AGUAAAAMAAAAAQAAAAQAAAgQ"
        },
        "BlockData": {
          "__b64": "ZXh0cm5saWQzODhGN0RCQjE0MjY0MDg3ODk5N0U4OTc2QjQxNkQxRQ=="
        }
      },
      {
        "_PW_ID": 43,
        "MainId": 33,
        "CanvasId": 2,
        "LayerId": 6,
        "Attribute": {
          "__b64": "AAAAEAAAAGYAAAAqAAAAMgAAAAkAUABhAHIAYQBtAGUAdABlAHIAAAIAAAACAAAAAAIAAAACAAAAIQAAAAEAAAAEAAAABQABAAAAAAAEAAAEAAAAAAEAAAEAAAEAAAAAAQAAAAEAAAAACAAAAAgAAAAAAAAAAAAAAAkASQBuAGkAdABDAG8AbABvAHIAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAkAQgBsAG8AYwBrAFMAaQB6AGUAAAAMAAAABAAAAAQAAABoAAAhHwAAAGgAAABo"
        },
        "BlockData": {
          "__b64": "ZXh0cm5saWRDMzZBRTY0NEQ1RUM0RjBBQjI3RTk3RTg5QzYwQ0JFNA=="
        }
      }
    ],
    "thumbnailRows": [
      {
        "_PW_ID": 6,
        "MainId": 6,
        "CanvasId": 2,
        "LayerId": 6,
        "ThumbnailSmallerNeedRefresh": 131,
        "ThumbnailSmallNeedRefresh": 131,
        "ThumbnailMiddleNeedRefresh": 131,
        "ThumbnailLargeNeedRefresh": 131,
        "ThumbnailLargerNeedRefresh": 131,
        "ThumbnailMiddle2xNeedRefresh": 131,
        "ThumbnailLarger2xNeedRefresh": 131,
        "ThumbnailSmallerNeedRefresh1": 0,
        "ThumbnailSmallNeedRefresh1": 132,
        "ThumbnailMiddleNeedRefresh1": 132,
        "ThumbnailLargeNeedRefresh1": 132,
        "ThumbnailLargerNeedRefresh1": 0,
        "ThumbnailMiddle2xNeedRefresh1": 132,
        "ThumbnailLarger2xNeedRefresh1": 132,
        "ThumbnailDrewMode": 0,
        "ThumbnailFixMode": 0,
        "ThumbnailCanvasWidth": 1518,
        "ThumbnailCanvasHeight": 2150,
        "ThumbnailUseDrawColor": 0,
        "ThumbnailMainColorRed": 0,
        "ThumbnailMainColorGreen": 0,
        "ThumbnailMainColorBlue": 0,
        "ThumbnailSubColorRed": 0,
        "ThumbnailSubColorGreen": 0,
        "ThumbnailSubColorBlue": 0,
        "ThumbnailOffscreen": 33,
        "ThumbnailColorTypeIndex": 0,
        "ThumbnailColorTypeBlack": 1,
        "ThumbnailColorTypeWhite": 1,
        "ThumbnailPrewviewColorTypeIndex": 0,
        "ThumbnailPrewviewColorTypeBlack": 1,
        "ThumbnailPrewviewColorTypeWhite": 1,
        "ThumbnailPrewviewColorTypeOpacity": 1,
        "ThumbnailPrewviewColorTypeImage": 2147483648,
        "ThumbnailPrewviewColorTypeAlpha": 2147483648,
        "ThumbnailPrewviewMaskBinarize": 0,
        "ThumbnailPrewviewMaskThreshold": 2147483648,
        "ThumbnailDrewUseCanvasAspect0": 1,
        "ThumbnailDrewUseCanvasAspect1": 0
      }
    ]
  },
  7:   {
    "layer": {
      "_PW_ID": 7,
      "MainId": 7,
      "CanvasId": 2,
      "LayerName": "てすとてすとてすとてすと てすとてすとてすとてすと てすとてすとてすとてすと てすとてすとてすとてすと",
      "LayerType": 0,
      "LayerLock": 0,
      "LayerClip": 0,
      "LayerMasking": 0,
      "LayerOffsetX": 27,
      "LayerOffsetY": 592,
      "LayerRenderOffscrOffsetX": -27,
      "LayerRenderOffscrOffsetY": -592,
      "LayerMaskOffsetX": -27,
      "LayerMaskOffsetY": -592,
      "LayerMaskOffscrOffsetX": 0,
      "LayerMaskOffscrOffsetY": 0,
      "LayerOpacity": 256,
      "LayerComposite": 0,
      "LayerUsePaletteColor": 0,
      "LayerNoticeablePaletteColor": 0,
      "LayerPaletteRed": 0,
      "LayerPaletteGreen": 0,
      "LayerPaletteBlue": 0,
      "LayerFolder": 0,
      "LayerVisibility": 1,
      "LayerSelect": 0,
      "LayerNextIndex": 0,
      "LayerFirstChildIndex": 0,
      "LayerUuid": "9bac89967f-ac4b-94b7-fcec-f8efe1dd01",
      "LayerRenderMipmap": 7,
      "LayerLayerMaskMipmap": 0,
      "LayerRenderThumbnail": 7,
      "LayerLayerMaskThumbnail": 0,
      "UsePreviewColorType": null,
      "UsePreviewMaskColorType": null,
      "EffectRangeType": null,
      "DraftLayer": null,
      "FilterLayerV132": null,
      "FilterLayerColorMixingInfo": null,
      "GradationFillColorMixingInfo": null,
      "LayerColorTypeIndex": 0,
      "LayerColorTypeBlackChecked": 1,
      "LayerColorTypeWhiteChecked": 1,
      "MaterialContentType": 110,
      "DrawToRenderOffscreenType": 40,
      "DrawToRenderMipmapType": 40,
      "MoveOffsetAndExpandType": 50,
      "TextLayerType": 0,
      "TextLayerString": {
        "__b64": "44Gm44GZ44Go44Gm44GZ44Go44Gm44GZ44Go44Gm44GZ44GoDQrjgabjgZnjgajjgabjgZnjgajjgabjgZnjgajjgabjgZnjgagNCuOBpuOBmeOBqOOBpuOBmeOBqOOBpuOBmeOBqOOBpuOBmeOBqA0K44Gm44GZ44Go44Gm44GZ44Go44Gm44GZ44Go44Gm44GZ44Go"
      },
      "TextLayerAttributes": {
        "__b64": "CwAAAEAAAAABAAAAAAAAADYAAAA4AAAAAAMAAAAAAAAAAAAAAABZQA8ASQAtAE8AVABGAKIw8zDBMMMwrzBTAHQAZAAgAEIAGgAAACAAAAABAAAAAAAAADYAAAAQAAAAAAAAAAAAWUAAAAAAAABZQBEAAAAAAAAADAAAABIAAAABAAAAAAAAADYAAAACAAAAAAANAAAAIgAAAAEAAAAAAAAANgAAABIAAAAAAKzVarVarQZAAAAAAAAAWUAOAAAAAAAAABsAAAAAAAAAHAAAAAAAAAAdAAAAEgAAAAEAAAAAAAAANgAAAAIAAAABAEEAAAASAAAAAQAAAAAAAAA2AAAAAgAAAAEAHgAAAAQBAAAQAAAAAAAAAAMAAAAEAAAAAAAAAAMAAAADAAAABAAAAAAAAAAGAAAAAwAAAAQAAAAAAAAACQAAAAUAAAAEAAAAAAAAAA4AAAADAAAABAAAAAAAAAARAAAAAwAAAAQAAAAAAAAAFAAAAAMAAAAEAAAAAAAAABcAAAAFAAAABAAAAAAAAAAcAAAAAwAAAAQAAAAAAAAAHwAAAAMAAAAEAAAAAAAAACIAAAADAAAABAAAAAAAAAAlAAAABQAAAAQAAAAAAAAAKgAAAAMAAAAEAAAAAAAAAC0AAAADAAAABAAAAAAAAAAwAAAAAwAAAAQAAAAAAAAAMwAAAAMAAAAEAAAAAAAAAA8AAAAAAAAAEwAAAAAAAAAQAAAAEgAAAAEAAAAAAAAANgAAAAIAAAAAABQAAAASAAAAAQAAAAAAAAA2AAAAAgAAAAAAEgAAABIAAAABAAAAAAAAADYAAAACAAAAAAAVAAAAAAAAABYAAAAAAAAAHwAAABkAAABJLU9URuOCouODs+ODgeODg+OCr1N0ZCBCIAAAAAQAAACNAQAAIQAAAAQAAAAQAAAAIgAAAAwAAAAAAAAAAAAAAAAAAAAjAAAABAAAAAAAAAAlAAAABAAAABsBAAAsAAAABAAAAI0gAAAmAAAABAAAAAQAAAArAAAABAAAADIAAAAnAAAACAAAADYAAAAAAAAAKAAAAAAAAAApAAAAAAAAACoAAAAQAAAA6wIAAP0BAAC3AwAAiwMAAC0AAAAEAAAAAAAAAC4AAAAEAAAAAAAAAC8AAAApAAAACQAyAAAAAAAAAB0A77yt77yzIO+8sOOCtOOCt+ODg+OCryDmqJnmupYwAAAABAAAAAEAAAA1AAAABAAAAAAAAAA3AAAABAAAAAAAAAA0AAAABAAAAAEAAAA2AAAAFAAAAAAAAAAAAAAAAAAAAAAAAAD/////OAAAABgAAAAAAAAAkAEAAAIAAAAAAAAAAAAAAAAAAAAxAAAABAAAAOsDAAAyAAAABAAAAAAAAAAzAAAABAAAAAAAAAA5AAAAKwAAAAEAGQBJLU9URuOCouODs+ODgeODg+OCr1N0ZCBCDABJd2FBbnRTdGQtQmQ6AAAABAAAAAgHAAA7AAAABAAAAIQDAAA8AAAABAAAAIQDAAA9AAAABAAAAAAAAAA+AAAABAAAAAAAAAA/AAAACAAAAMwAAACOAQAAQAAAACAAAAC0sP//AAAAAGQAAAAAAAAAZAAAAHibAAC0sP//eJsAAEIAAAAEAAAAAAAAAEMAAAAEAAAA6AMAAEQAAAAEAAAAAAAAAEUAAAAEAAAAAAAAAEYAAAAIAAAAAAAAAAAAAABHAAAACAAAAEB2gAAAAAAASAAAAAgAAADLAAAAAAAAAEkAAAAEAAAAAQAAAEoAAAAEAAAAAAAAAA=="
      },
      "TextLayerStringArray": null,
      "TextLayerAttributesArray": null,
      "TextLayerAddAttributesV01": {
        "__b64": "GAQAAAsAAAAWAAAAAQAAAA4AAAAAAwEAAAAAAAAAAAAAABoAAAAMAAAAAQAAAAQAAAABAAAAEQAAAAAAAAAMAAAADAAAAAEAAAAEAAAAAQAAAA0AAAAMAAAAAQAAAAQAAAABAAAADgAAAAAAAAAbAAAAAAAAABwAAAAAAAAAHQAAAAwAAAABAAAABAAAAAEAAABBAAAADAAAAAEAAAAEAAAAAQAAAB4AAACEAAAAEAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAADwAAAAAAAAATAAAAAAAAABAAAAAMAAAAAQAAAAQAAAABAAAAFAAAAAwAAAABAAAABAAAAAEAAAASAAAADAAAAAEAAAAEAAAAAQAAABUAAAAAAAAAFgAAAAAAAAAfAAAAGQAAAEktT1RG44Ki44Oz44OB44OD44KvU3RkIEIgAAAABAAAAI0BAAAhAAAABAAAABAAAAAiAAAADAAAAAAAAAAAAAAAAAAAACMAAAAEAAAAAAAAACUAAAAEAAAAGwEAACwAAAAEAAAAjSAAACYAAAAEAAAABAAAACsAAAAEAAAAMgAAACcAAAAIAAAANgAAAAAAAAAoAAAAAAAAACkAAAAAAAAAKgAAABAAAADrAgAA/QEAALcDAACLAwAALQAAAAQAAAAAAAAALgAAAAQAAAAAAAAALwAAACkAAAAJADIAAAAAAAAAHQDvvK3vvLMg77yw44K044K344OD44KvIOaomea6ljAAAAAEAAAAAQAAADUAAAAEAAAAAAAAADcAAAAEAAAAAAAAADQAAAAEAAAAAQAAADYAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAP////84AAAAGAAAAAAAAACQAQAAAgAAAAAAAAAAAAAAAAAAADEAAAAEAAAA6wMAADIAAAAEAAAAAAAAADMAAAAEAAAAAAAAADkAAAAAAAAAOgAAAAQAAAAIBwAAOwAAAAQAAACEAwAAPAAAAAQAAACEAwAAPQAAAAQAAAAAAAAAPgAAAAQAAAAAAAAAPwAAAAgAAADMAAAAjgEAAEAAAAAgAAAAtLD//wAAAABkAAAAAAAAAGQAAAB4mwAAtLD//3ibAABCAAAABAAAAAAAAABDAAAABAAAAOgDAABEAAAABAAAAAAAAABFAAAABAAAAAAAAABGAAAACAAAAAAAAAAAAAAARwAAAAgAAABAdoAAAAAAAEgAAAAIAAAAywAAAAAAAABJAAAABAAAAAEAAABKAAAABAAAAAAAAAA="
      },
      "TextLayerAttributesVersion": 1,
      "TextLayerVersion": null,
      "TextLayerNameAutoChangeEnabled": 1
    },
    "blobs": {
      "attributes": {
        "__b64": "CwAAAEAAAAABAAAAAAAAADYAAAA4AAAAAAMAAAAAAAAAAAAAAABZQA8ASQAtAE8AVABGAKIw8zDBMMMwrzBTAHQAZAAgAEIAGgAAACAAAAABAAAAAAAAADYAAAAQAAAAAAAAAAAAWUAAAAAAAABZQBEAAAAAAAAADAAAABIAAAABAAAAAAAAADYAAAACAAAAAAANAAAAIgAAAAEAAAAAAAAANgAAABIAAAAAAKzVarVarQZAAAAAAAAAWUAOAAAAAAAAABsAAAAAAAAAHAAAAAAAAAAdAAAAEgAAAAEAAAAAAAAANgAAAAIAAAABAEEAAAASAAAAAQAAAAAAAAA2AAAAAgAAAAEAHgAAAAQBAAAQAAAAAAAAAAMAAAAEAAAAAAAAAAMAAAADAAAABAAAAAAAAAAGAAAAAwAAAAQAAAAAAAAACQAAAAUAAAAEAAAAAAAAAA4AAAADAAAABAAAAAAAAAARAAAAAwAAAAQAAAAAAAAAFAAAAAMAAAAEAAAAAAAAABcAAAAFAAAABAAAAAAAAAAcAAAAAwAAAAQAAAAAAAAAHwAAAAMAAAAEAAAAAAAAACIAAAADAAAABAAAAAAAAAAlAAAABQAAAAQAAAAAAAAAKgAAAAMAAAAEAAAAAAAAAC0AAAADAAAABAAAAAAAAAAwAAAAAwAAAAQAAAAAAAAAMwAAAAMAAAAEAAAAAAAAAA8AAAAAAAAAEwAAAAAAAAAQAAAAEgAAAAEAAAAAAAAANgAAAAIAAAAAABQAAAASAAAAAQAAAAAAAAA2AAAAAgAAAAAAEgAAABIAAAABAAAAAAAAADYAAAACAAAAAAAVAAAAAAAAABYAAAAAAAAAHwAAABkAAABJLU9URuOCouODs+ODgeODg+OCr1N0ZCBCIAAAAAQAAACNAQAAIQAAAAQAAAAQAAAAIgAAAAwAAAAAAAAAAAAAAAAAAAAjAAAABAAAAAAAAAAlAAAABAAAABsBAAAsAAAABAAAAI0gAAAmAAAABAAAAAQAAAArAAAABAAAADIAAAAnAAAACAAAADYAAAAAAAAAKAAAAAAAAAApAAAAAAAAACoAAAAQAAAA6wIAAP0BAAC3AwAAiwMAAC0AAAAEAAAAAAAAAC4AAAAEAAAAAAAAAC8AAAApAAAACQAyAAAAAAAAAB0A77yt77yzIO+8sOOCtOOCt+ODg+OCryDmqJnmupYwAAAABAAAAAEAAAA1AAAABAAAAAAAAAA3AAAABAAAAAAAAAA0AAAABAAAAAEAAAA2AAAAFAAAAAAAAAAAAAAAAAAAAAAAAAD/////OAAAABgAAAAAAAAAkAEAAAIAAAAAAAAAAAAAAAAAAAAxAAAABAAAAOsDAAAyAAAABAAAAAAAAAAzAAAABAAAAAAAAAA5AAAAKwAAAAEAGQBJLU9URuOCouODs+ODgeODg+OCr1N0ZCBCDABJd2FBbnRTdGQtQmQ6AAAABAAAAAgHAAA7AAAABAAAAIQDAAA8AAAABAAAAIQDAAA9AAAABAAAAAAAAAA+AAAABAAAAAAAAAA/AAAACAAAAMwAAACOAQAAQAAAACAAAAC0sP//AAAAAGQAAAAAAAAAZAAAAHibAAC0sP//eJsAAEIAAAAEAAAAAAAAAEMAAAAEAAAA6AMAAEQAAAAEAAAAAAAAAEUAAAAEAAAAAAAAAEYAAAAIAAAAAAAAAAAAAABHAAAACAAAAEB2gAAAAAAASAAAAAgAAADLAAAAAAAAAEkAAAAEAAAAAQAAAEoAAAAEAAAAAAAAAA=="
      },
      "addAttributes": {
        "__b64": "GAQAAAsAAAAWAAAAAQAAAA4AAAAAAwEAAAAAAAAAAAAAABoAAAAMAAAAAQAAAAQAAAABAAAAEQAAAAAAAAAMAAAADAAAAAEAAAAEAAAAAQAAAA0AAAAMAAAAAQAAAAQAAAABAAAADgAAAAAAAAAbAAAAAAAAABwAAAAAAAAAHQAAAAwAAAABAAAABAAAAAEAAABBAAAADAAAAAEAAAAEAAAAAQAAAB4AAACEAAAAEAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAADwAAAAAAAAATAAAAAAAAABAAAAAMAAAAAQAAAAQAAAABAAAAFAAAAAwAAAABAAAABAAAAAEAAAASAAAADAAAAAEAAAAEAAAAAQAAABUAAAAAAAAAFgAAAAAAAAAfAAAAGQAAAEktT1RG44Ki44Oz44OB44OD44KvU3RkIEIgAAAABAAAAI0BAAAhAAAABAAAABAAAAAiAAAADAAAAAAAAAAAAAAAAAAAACMAAAAEAAAAAAAAACUAAAAEAAAAGwEAACwAAAAEAAAAjSAAACYAAAAEAAAABAAAACsAAAAEAAAAMgAAACcAAAAIAAAANgAAAAAAAAAoAAAAAAAAACkAAAAAAAAAKgAAABAAAADrAgAA/QEAALcDAACLAwAALQAAAAQAAAAAAAAALgAAAAQAAAAAAAAALwAAACkAAAAJADIAAAAAAAAAHQDvvK3vvLMg77yw44K044K344OD44KvIOaomea6ljAAAAAEAAAAAQAAADUAAAAEAAAAAAAAADcAAAAEAAAAAAAAADQAAAAEAAAAAQAAADYAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAP////84AAAAGAAAAAAAAACQAQAAAgAAAAAAAAAAAAAAAAAAADEAAAAEAAAA6wMAADIAAAAEAAAAAAAAADMAAAAEAAAAAAAAADkAAAAAAAAAOgAAAAQAAAAIBwAAOwAAAAQAAACEAwAAPAAAAAQAAACEAwAAPQAAAAQAAAAAAAAAPgAAAAQAAAAAAAAAPwAAAAgAAADMAAAAjgEAAEAAAAAgAAAAtLD//wAAAABkAAAAAAAAAGQAAAB4mwAAtLD//3ibAABCAAAABAAAAAAAAABDAAAABAAAAOgDAABEAAAABAAAAAAAAABFAAAABAAAAAAAAABGAAAACAAAAAAAAAAAAAAARwAAAAgAAABAdoAAAAAAAEgAAAAIAAAAywAAAAAAAABJAAAABAAAAAEAAABKAAAABAAAAAAAAAA="
      }
    },
    "mipmapRows": [
      {
        "_PW_ID": 7,
        "MainId": 7,
        "CanvasId": 2,
        "LayerId": 7,
        "MipmapCount": 6,
        "BaseMipmapInfo": 32
      }
    ],
    "mipmapInfoRows": [
      {
        "_PW_ID": 37,
        "MainId": 32,
        "CanvasId": 2,
        "LayerId": 7,
        "ThisScale": 100,
        "Offscreen": 40,
        "NextIndex": 33
      },
      {
        "_PW_ID": 38,
        "MainId": 33,
        "CanvasId": 2,
        "LayerId": 7,
        "ThisScale": 50,
        "Offscreen": 42,
        "NextIndex": 34
      },
      {
        "_PW_ID": 39,
        "MainId": 34,
        "CanvasId": 2,
        "LayerId": 7,
        "ThisScale": 25,
        "Offscreen": 43,
        "NextIndex": 35
      },
      {
        "_PW_ID": 40,
        "MainId": 35,
        "CanvasId": 2,
        "LayerId": 7,
        "ThisScale": 12.5,
        "Offscreen": 44,
        "NextIndex": 36
      },
      {
        "_PW_ID": 41,
        "MainId": 36,
        "CanvasId": 2,
        "LayerId": 7,
        "ThisScale": 6.25,
        "Offscreen": 45,
        "NextIndex": 37
      },
      {
        "_PW_ID": 42,
        "MainId": 37,
        "CanvasId": 2,
        "LayerId": 7,
        "ThisScale": 3.125,
        "Offscreen": 46,
        "NextIndex": 0
      }
    ],
    "offscreenRows": [
      {
        "_PW_ID": 45,
        "MainId": 40,
        "CanvasId": 2,
        "LayerId": 7,
        "Attribute": {
          "__b64": "AAAAEAAAAGYAAAAqAAAA+gAAAAkAUABhAHIAYQBtAGUAdABlAHIAAAXuAAAIZgAAAAYAAAAJAAAAIQAAAAEAAAAEAAAABQABAAAAAAAEAAAEAAAAAAEAAAEAAAEAAAAAAQAAAAEAAAAACAAAAAgAAAAAAAAAAAAAAAkASQBuAGkAdABDAG8AbABvAHIAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAkAQgBsAG8AYwBrAFMAaQB6AGUAAAAMAAAANgAAAAQAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAAYdAAAAaAAAAGgAAABoAAAGHQAABh0AAAYdAAAAaAAAAGgAAABoAAAGHQAABh0AAAYdAAAAaAAAAGgAAABoAAAAaAAABh0AACDVAAAAaAAAAGgAAABoAAAAaAAAAGgAACTaAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGg="
        },
        "BlockData": {
          "__b64": "ZXh0cm5saWRGN0QxRkQzRkFEQUE0RTg5Qjc1OTM0OUIyMDFDMjNFOA=="
        }
      },
      {
        "_PW_ID": 46,
        "MainId": 42,
        "CanvasId": 2,
        "LayerId": 7,
        "Attribute": {
          "__b64": "AAAAEAAAAGYAAAAqAAAAXgAAAAkAUABhAHIAYQBtAGUAdABlAHIAAAL3AAAEMwAAAAMAAAAFAAAAIQAAAAEAAAAEAAAABQABAAAAAAAEAAAEAAAAAAEAAAEAAAEAAAAAAQAAAAEAAAAACAAAAAgAAAAAAAAAAAAAAAkASQBuAGkAdABDAG8AbABvAHIAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAkAQgBsAG8AYwBrAFMAaQB6AGUAAAAMAAAADwAAAAQAAABoAAAGHQAAAGgAAAkSAAAK/gAAAGgAAABoAAAh+AAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGg="
        },
        "BlockData": {
          "__b64": "ZXh0cm5saWQ2QjY5QzgzNTI2MjA0MDU0QkVBMDQ0NDgxRjNGRTBDNw=="
        }
      },
      {
        "_PW_ID": 47,
        "MainId": 43,
        "CanvasId": 2,
        "LayerId": 7,
        "Attribute": {
          "__b64": "AAAAEAAAAGYAAAAqAAAAOgAAAAkAUABhAHIAYQBtAGUAdABlAHIAAAF7AAACGQAAAAIAAAADAAAAIQAAAAEAAAAEAAAABQABAAAAAAAEAAAEAAAAAAEAAAEAAAEAAAAAAQAAAAEAAAAACAAAAAgAAAAAAAAAAAAAAAkASQBuAGkAdABDAG8AbABvAHIAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAkAQgBsAG8AYwBrAFMAaQB6AGUAAAAMAAAABgAAAAQAAAfZAAAAaAAAGDQAAABoAAAAaAAAAGg="
        },
        "BlockData": {
          "__b64": "ZXh0cm5saWQzMTVDMTNEN0UzMzM0OTc1QTQ1QjA1OERDQzRFOUZEMQ=="
        }
      },
      {
        "_PW_ID": 48,
        "MainId": 44,
        "CanvasId": 2,
        "LayerId": 7,
        "Attribute": {
          "__b64": "AAAAEAAAAGYAAAAqAAAAKgAAAAkAUABhAHIAYQBtAGUAdABlAHIAAAC9AAABDAAAAAEAAAACAAAAIQAAAAEAAAAEAAAABQABAAAAAAAEAAAEAAAAAAEAAAEAAAEAAAAAAQAAAAEAAAAACAAAAAgAAAAAAAAAAAAAAAkASQBuAGkAdABDAG8AbABvAHIAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAkAQgBsAG8AYwBrAFMAaQB6AGUAAAAMAAAAAgAAAAQAABKuAAAAaA=="
        },
        "BlockData": {
          "__b64": "ZXh0cm5saWRDRTQyREEyQUU0MjY0OTZEQUIxRDc4MUU3NjA0NDhBMA=="
        }
      },
      {
        "_PW_ID": 49,
        "MainId": 45,
        "CanvasId": 2,
        "LayerId": 7,
        "Attribute": {
          "__b64": "AAAAEAAAAGYAAAAqAAAAJgAAAAkAUABhAHIAYQBtAGUAdABlAHIAAABeAAAAhgAAAAEAAAABAAAAIQAAAAEAAAAEAAAABQABAAAAAAAEAAAEAAAAAAEAAAEAAAEAAAAAAQAAAAEAAAAACAAAAAgAAAAAAAAAAAAAAAkASQBuAGkAdABDAG8AbABvAHIAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAkAQgBsAG8AYwBrAFMAaQB6AGUAAAAMAAAAAQAAAAQAAAyL"
        },
        "BlockData": {
          "__b64": "ZXh0cm5saWQxQjhGQzE4QUJGMEQ0M0ZEQUFGNDM0N0M4QjY4QkY3QQ=="
        }
      },
      {
        "_PW_ID": 50,
        "MainId": 46,
        "CanvasId": 2,
        "LayerId": 7,
        "Attribute": {
          "__b64": "AAAAEAAAAGYAAAAqAAAAJgAAAAkAUABhAHIAYQBtAGUAdABlAHIAAAAvAAAAQwAAAAEAAAABAAAAIQAAAAEAAAAEAAAABQABAAAAAAAEAAAEAAAAAAEAAAEAAAEAAAAAAQAAAAEAAAAACAAAAAgAAAAAAAAAAAAAAAkASQBuAGkAdABDAG8AbABvAHIAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAkAQgBsAG8AYwBrAFMAaQB6AGUAAAAMAAAAAQAAAAQAAAiW"
        },
        "BlockData": {
          "__b64": "ZXh0cm5saWQzMDQ4QjVCRDQ4QkM0RjNFODRBREUyNjM4NjhDNUZCRg=="
        }
      },
      {
        "_PW_ID": 51,
        "MainId": 41,
        "CanvasId": 2,
        "LayerId": 7,
        "Attribute": {
          "__b64": "AAAAEAAAAGYAAAAqAAAAMgAAAAkAUABhAHIAYQBtAGUAdABlAHIAAAIAAAACAAAAAAIAAAACAAAAIQAAAAEAAAAEAAAABQABAAAAAAAEAAAEAAAAAAEAAAEAAAEAAAAAAQAAAAEAAAAACAAAAAgAAAAAAAAAAAAAAAkASQBuAGkAdABDAG8AbABvAHIAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAkAQgBsAG8AYwBrAFMAaQB6AGUAAAAMAAAABAAAAAQAAABoAAAkMQAAAGgAAABo"
        },
        "BlockData": {
          "__b64": "ZXh0cm5saWRBNEYwNDQ1M0Y5Q0E0OTZEOEVERUJGNDAwNjQzRkUyQg=="
        }
      }
    ],
    "thumbnailRows": [
      {
        "_PW_ID": 7,
        "MainId": 7,
        "CanvasId": 2,
        "LayerId": 7,
        "ThumbnailSmallerNeedRefresh": 103,
        "ThumbnailSmallNeedRefresh": 103,
        "ThumbnailMiddleNeedRefresh": 103,
        "ThumbnailLargeNeedRefresh": 103,
        "ThumbnailLargerNeedRefresh": 103,
        "ThumbnailMiddle2xNeedRefresh": 103,
        "ThumbnailLarger2xNeedRefresh": 103,
        "ThumbnailSmallerNeedRefresh1": 0,
        "ThumbnailSmallNeedRefresh1": 104,
        "ThumbnailMiddleNeedRefresh1": 104,
        "ThumbnailLargeNeedRefresh1": 104,
        "ThumbnailLargerNeedRefresh1": 0,
        "ThumbnailMiddle2xNeedRefresh1": 104,
        "ThumbnailLarger2xNeedRefresh1": 104,
        "ThumbnailDrewMode": 0,
        "ThumbnailFixMode": 0,
        "ThumbnailCanvasWidth": 1518,
        "ThumbnailCanvasHeight": 2150,
        "ThumbnailUseDrawColor": 0,
        "ThumbnailMainColorRed": 0,
        "ThumbnailMainColorGreen": 0,
        "ThumbnailMainColorBlue": 0,
        "ThumbnailSubColorRed": 0,
        "ThumbnailSubColorGreen": 0,
        "ThumbnailSubColorBlue": 0,
        "ThumbnailOffscreen": 41,
        "ThumbnailColorTypeIndex": 0,
        "ThumbnailColorTypeBlack": 1,
        "ThumbnailColorTypeWhite": 1,
        "ThumbnailPrewviewColorTypeIndex": 0,
        "ThumbnailPrewviewColorTypeBlack": 1,
        "ThumbnailPrewviewColorTypeWhite": 1,
        "ThumbnailPrewviewColorTypeOpacity": 1,
        "ThumbnailPrewviewColorTypeImage": 2147483648,
        "ThumbnailPrewviewColorTypeAlpha": 2147483648,
        "ThumbnailPrewviewMaskBinarize": 0,
        "ThumbnailPrewviewMaskThreshold": 2147483648,
        "ThumbnailDrewUseCanvasAspect0": 1,
        "ThumbnailDrewUseCanvasAspect1": 0
      }
    ]
  }
};

function hydrate(raw: RawSnapshot): TextLayerTemplate {
  return {
    layer: jsonToRow(raw.layer),
    blobs: {
      attributes: b64(raw.blobs.attributes.__b64),
      addAttributes: b64(raw.blobs.addAttributes.__b64),
    },
    mipmapRows: jsonRows(raw.mipmapRows),
    mipmapInfoRows: jsonRows(raw.mipmapInfoRows),
    offscreenRows: jsonRows(raw.offscreenRows),
    thumbnailRows: jsonRows(raw.thumbnailRows),
  };
}

export const TEXT_LAYER_PROTOTYPES = new Map<number, TextLayerTemplate>([
  [5, hydrate(RAW['5'])],
  [6, hydrate(RAW['6'])],
  [7, hydrate(RAW['7'])],
]);

export function getTextLayerPrototype(mainId: 5 | 6 | 7): TextLayerTemplate {
  const t = TEXT_LAYER_PROTOTYPES.get(mainId);
  if (!t) {
    throw new Error(`Text layer prototype MainId=${mainId} missing — run npm run clip:template:build`);
  }
  return t;
}
